# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_sport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10user_sport.proto\"\x18\n\x08UserName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xad\x01\n\x06Sports\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x1a\n\x02tr\x18\x02 \x01(\x0b\x32\x0e.Sports.Trener\x12\n\n\x02sp\x18\x03 \x01(\t\x12\x1b\n\x02st\x18\x04 \x03(\x0b\x32\x0f.Sports.StEntry\x1a\x15\n\x06Trener\x12\x0b\n\x03\x66io\x18\x01 \x01(\t\x1a\x39\n\x07StEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.Sports.Trener:\x02\x38\x01\"\x17\n\nMaxRequest\x12\t\n\x01\x63\x18\x01 \x01(\x05\" \n\x08\x41llSport\x12\x14\n\x03spt\x18\x01 \x03(\x0b\x32\x07.Sports2P\n\tSportLive\x12\x1e\n\x08GetSport\x12\t.UserName\x1a\x07.Sports\x12#\n\tAllSports\x12\x0b.MaxRequest\x1a\t.AllSportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_sport_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _SPORTS_STENTRY._options = None
  _SPORTS_STENTRY._serialized_options = b'8\001'
  _globals['_USERNAME']._serialized_start=20
  _globals['_USERNAME']._serialized_end=44
  _globals['_SPORTS']._serialized_start=47
  _globals['_SPORTS']._serialized_end=220
  _globals['_SPORTS_TRENER']._serialized_start=140
  _globals['_SPORTS_TRENER']._serialized_end=161
  _globals['_SPORTS_STENTRY']._serialized_start=163
  _globals['_SPORTS_STENTRY']._serialized_end=220
  _globals['_MAXREQUEST']._serialized_start=222
  _globals['_MAXREQUEST']._serialized_end=245
  _globals['_ALLSPORT']._serialized_start=247
  _globals['_ALLSPORT']._serialized_end=279
  _globals['_SPORTLIVE']._serialized_start=281
  _globals['_SPORTLIVE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
